### ISSUE TITLE
Error running phyloMed

### ISSUE THREAD

**Issue by choon-sim** [KiRinHong/miMediation#2]
Hello, I am running phyloMed using a taxonomy table to represent the tree. I ran into 2 types of errors. When I use a binary vector comprising (0,1) for both treatment and outcome, it will say "processing internal node", and then stop running and produce an error message "Error in summary(glm(outcome ~ G + cbind(conf[, -1], Trt), family = "binomial"))$coefficients[1 +  :   subscript out of bounds". 

On the other hand, when I use a continuous numerical vector comprising (0,1,2,3,4) for the outcome, the error message is "Error in eval(family$initialize) : y values must be 0 <= y <= 1".

Any help will be appreciated.

**Comment by KiRinHong** [comment]
Hi, could you provide a demo data so that I can reproduce the error and troubleshoot it for you?

**Comment by choon-sim** [comment]
Hi, thanks for replying. Can you provide an email address so that I can send files over? I am not so willing to post my files on the site.

**Comment by choon-sim** [comment]
I found your email on your profile page, and have sent the files over. Thanks!

**Comment by KiRinHong** [comment]
The issue has been resolved. Please refer to News (version 0.3) in README.
